# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# These overrides are appropriate defaults for deploying this chart on OpenShift

global:
  openshift: true

server:
  image:
    repository: "quay.io/enclaive/vhsm"
    tag: "v1.4.4-1"

  readinessProbe:
    path: "/v1/sys/health?uninitcode=204"
