# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# These overrides are appropriate defaults for deploying this chart on OpenShift

global:
  openshift: true

server:
  readinessProbe:
    path: "/v1/sys/health?uninitcode=204"
